### ISSUE TITLE
MailClient::FolderRename does not allow "imap rename" to other parent

### ISSUE THREAD

**Issue by kengu** [detochko/MailSo#2]
Current implementation of `MailClient::FolderRename` does not allow to change folder parent. Renaming a folder from `Path\To\Parent1\Folder1` to `Path\To\Parent2\Folder2` is not allowed, although following imap commands do allow it

```
> telnet server 143
> .login username password
> .rename Path\To\Parent1\Folder1 Path\To\Parent2\Folder2
> .logout
```

**Comment by kengu** [comment]
I'll post a patch as a pull request soon.

**Comment by detochko** [comment]
This function has the functionality that was designed.
Maybe you just need to implement function MailClient::FolderMove or something like that.

I do not quite understand why you need to rename the folder tree entirely.
If we are talking about the user interface, there are usually available 2 operations (rename, and move).
MailClient closer to the program's mail, not IMAP commands.

**Comment by kengu** [comment]
My point was to implement the same behaviour as IMAP, but I do agree that FolderMove is more readable. Do you want me to do the change and re-post the pull-request?

**Comment by detochko** [comment]
1) Yes,  better to make a separate pull request with FolderMove functionality.
2) I can not accept the "predefined imap-search criterias", the reason I described in previous pull request .

**Comment by kengu** [comment]
1) OK, I'll close it and make a separate pull request
2) OK, I'll make a new branch without "predefined imap-search criterias" and commit from this instead.
